# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: SimonTatham.Puzzles
PackageVersion: 20221210.a3310ab
PackageLocale: en-US
Publisher: Simon Tatham
PackageName: Simon Tatham's Portable Puzzle Collection
License: MIT License
ShortDescription: A collection of small computer programs which implement one-player puzzle games.
ManifestType: defaultLocale
ManifestVersion: 1.2.0

